import "./Main.css"
import Barbour from "../../Assets/Assets/img/barbour.png"
import kate from "../../Assets/Assets/img/kate.png"
import lvmn from "../../Assets/Assets/img/lvmh.png"
import estee from "../../Assets/Assets/img/estee.png"
import tjx from "../../Assets/Assets/img/tjx.png"
import river from "../../Assets/Assets/img/river.png"
import radisson from "../../Assets/Assets/img/radisson.png"
import gstar from "../../Assets/Assets/img/g-star.png"
import main from "../../Assets/Assets/img/main.png"
import people from "../../Assets/Assets/img/people.png"
import mountine from "../../Assets/Assets/img/mountine.png"
import notebook from "../../Assets/Assets/img/notebook.png"
import romb from "../../Assets/Assets/img/romb.png"
import curcle from "../../Assets/Assets/img/curcle.png"
import curcles from "../../Assets/Assets/img/curcles.png"


function Main() {
    return (
        <main>
            <section>

                <div class="container">
                    <p class="world">
                        Trusted by world-class brands.
                    </p>
                    <div class="main__div">

                        <img src={Barbour} alt="barbour" width="102" height="42" />
                        <img src={kate} alt="kate" width="97" height="42" />
                        <img src={lvmn} alt="lvmh" width="95" height="42" />
                        <img src={estee} alt="estee" width="115" height="37" />
                        <img src={tjx} alt="tjx" width="53" height="42" />
                        <img src={river} alt="river" width="115" height="37" />
                        <img src={radisson} alt="radisson" width="102" height="42" />
                        <img src={gstar} alt="g-star" width="115" height="37" />


                    </div>
                </div>

            </section>


            <section>

                <div class="container">

                    <div class="king">
                        <div class="grow">
                            <h3 class="faster">
                                Grow 2.5x faster than your competitors.
                            </h3>

                            <div class="book">
                                <a class="link" href="#">
                                    Book a demo
                                </a>

                                <p class="meet">
                                    Meet our customers
                                </p>
                            </div>

                            <p class="pwc">
                                *PwC audited methodology.
                            </p>

                            <p class="read">
                                Read the report
                            </p>

                        </div>

                        <div class="number">

                            <ul class="number__list">

                                <div class="section">

                                    <li class="number__item">
                                        <a href="#" class="number__link">

                                            <h2 class="number__title">
                                                140%
                                            </h2>

                                            <p class="number__text__1">
                                                Qubit's top customers annual growth rate.
                                            </p>

                                        </a>
                                    </li>

                                    <li class="number__item">
                                        <a href="#" class="number__link">

                                            <h2 class="number__title">
                                                $20bn
                                            </h2>

                                            <p class="number__text__2">
                                                Online sales generated by our customers in 2020.
                                            </p>

                                        </a>
                                    </li>

                                    <li class="number__item">
                                        <a href="#" class="number__link">

                                            <h2 class="number__title">
                                                364
                                            </h2>

                                            <p class="number__text__3">
                                                Ecommerce stores are growing faster with Qubit.
                                            </p>

                                        </a>
                                    </li>

                                </div>

                                <div class="more">
                                    <li class="number__item">
                                        <a href="#" class="number__link">

                                            <h2 class="number__title">
                                                9.5m
                                            </h2>

                                            <p class="number__text__4">
                                                Personalized experiences delivered every hour.
                                            </p>

                                        </a>
                                    </li>

                                    <li class="number__item">
                                        <a href="#" class="number__link">

                                            <h2 class="number__title">
                                                4.4m
                                            </h2>

                                            <p class="number__text__5">
                                                Shoppers influenced by Qubit every day.
                                            </p>

                                        </a>
                                    </li>

                                    <li class="number__item">
                                        <a href="#" class="number__link">

                                            <h2 class="number__title">
                                                $1.6bn
                                            </h2>

                                            <p class="number__text__6">
                                                Incremental revenue generated by our customers in 2020.*
                                            </p>

                                        </a>
                                    </li>

                                </div>


                            </ul>

                        </div>
                    </div>

                </div>


            </section>

            <section>

                <div class="container">

                    <div class="new">

                        <h3 class="mix">
                            Qubit CommerceAI.
                        </h3>

                        <p class="mix__text">
                            The new way to drive growth.
                        </p>

                    </div>

                    <div class="class">
                        <div class="cool">

                            <img src={main} alt="main" width="50" height="50" />



                            <h4 class="insight">
                                More insight
                            </h4>

                            <p class="learn">
                                Learn which products drive performance and which don't, through automated insights you can action.
                            </p>

                        </div>

                        <div class="cool">

                            <img src={people} alt="people" width="34" height="44" />



                            <h4 class="insight">
                                More personal
                            </h4>

                            <p class="personal">
                                Qubit CommerceAI generates a model per shopper to make every customer interaction more relevant.
                            </p>

                        </div>

                        <div class="cool">
                            <img src={mountine} alt="mountine" width="50" height="50" />


                            <h4 class="insight">
                                More effective
                            </h4>

                            <p class="data">
                                Qubit fuses data, intent, and design tools to enable your team to create more effective customer experiences.
                            </p>


                        </div>


                    </div>

                </div>



            </section>

            <section>

                <div class="container">

                    <div class="elements">

                        <h2 class="easy">
                            All the power. Easy to use.
                        </h2>

                        <p class="easy__text">
                            By collaborating with real ecommerce teams we've built the next-gen personalization tool. No code. No clunkiness.
                        </p>
                        <img src={notebook} alt="notebook" width="996" height="560" />

                    </div>

                    <div class="marker">

                        <a class="link" href="#">See products</a>

                        <a class="white" href="#">Book a demo</a>

                    </div>



                </div>

            </section>

            <section>

                <div class="container">

                    <div class="with">

                        <h2 class="product">
                            What you can do with Qubit.
                        </h2>

                    </div>

                    <div class="boss">

                        <div class="recamindation__div">

                            <img src={romb} alt="romb" />

                            <h3 class="recomendation">
                                1:1 Product recommendations
                            </h3>

                            <p class="recamindation__text">
                                Use deep learning recommendations to engage customers in seconds.
                            </p>
                        </div>

                        <div class="recamindation__div">
                            <img src={curcle} alt="curcle" />

                            <h3 class="badging">
                                1:1 Product badging
                            </h3>

                            <p class="badging__text">
                                Guide discovery with personalized product badging. Push sales with social proofing.
                            </p>
                        </div>

                        <div class="recamindation__div">
                            <img src={curcles} alt="curcles" />

                            <h3 class="content">
                                Personalized content
                            </h3>

                            <p class="content__text">
                                Your customers are unique. Present them with content that shows you know them.
                            </p>
                        </div>

                        <div class="recamindation__div">
                            <img src={main} alt="main" />

                            <h3 class="insinghts">
                                Product insights
                            </h3>

                            <p class="insinghts__text">
                                Your customers are unique. Present them with content that shows you know them.
                            </p>
                        </div>

                    </div>

                </div>

            </section>

        </main>
    )
}

export default Main;